# Generated by Django 6.1.1 on 2026-10-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_events', to='core.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'id'], name='bingo_event_room_id')],
            },
        ),
    ]
